version: "3.9"

services:
  hidra:
    build:
      context: .
      dockerfile: Dockerfile
    command: exporter /etc/hidra_exporter/exporter.yml
    environment:
      - OTEL_LOG_LEVEL=true
      - DEBUG=true
    working_dir: /app
    user: root
    volumes:
      - ./:/app
      - ./configs/hidra:/etc/hidra_exporter
    ports:
      - "19090:19090"
    expose:
      - 19090
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=hidratest
      - MINIO_SECRET_KEY=hidratest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001
  prometheus:
    image: prom/prometheus:v2.38.0
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    links:
      - hidra
    ports:
      - "9090:9090"

    expose:
      - 9090
  grafana:
    image: grafana/grafana:10.0.5
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    links:
      - prometheus
volumes:
  prometheus_data: {}
  grafana_data: {}
  minio_data: {}
