version: "3.9"

services:
  hidra:
    build:
      context: .
      dockerfile: Dockerfile
    command: -exporter -conf ./examples -maxExecutor 1
    #args: -exporter -conf ./examples -maxExecutor 1
    volumes:
      - ./examples:/examples
    ports:
      - "19090:19090"
    expose:
      - 19090
