version: "3.9"

services:
  hidra:
    build:
      context: .
      dockerfile: Dockerfile
    command: exporter configs/hidra/exporter.yml
    environment:
      - OTEL_LOG_LEVEL=true
      - DEBUG=true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "19090:19090"
    expose:
      - 19090
  prometheus:
    image: prom/prometheus:v2.38.0
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    links:
      - hidra
    ports:
      - "9090:9090"

    expose:
      - 9090
  grafana:
    image: grafana/grafana:9.1.3
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    links:
      - prometheus

  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: release-maker
    volumes:
      - ./:/app
    working_dir: /app
volumes:
  prometheus_data: {}
  grafana_data: {}
