version: "3.9"

services:
  hidra:
    build:
      context: .
      dockerfile: Dockerfile
    command: -exporter -conf ./examples -maxExecutor 8 -jaeger-endpoint http://jaeger:14268/api/traces
    environment:
      - OTEL_LOG_LEVEL=true
      - DEBUG=true
    volumes:
      - ./examples:/examples
    ports:
      - "19090:19090"
    expose:
      - 19090
    links:
      - jaeger
  prometheus:
    image: prom/prometheus:v2.33.4
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./etc/prometheus:/etc/prometheus
    links:
      - hidra
    ports:
      - "9090:9090"
    expose:
      - 9090
  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    expose:
      - 6831
      - 16686
      - 5778
      - 14268
