version: "3"

tasks:
  sync-git-prehooks:
    cmds:
      - cp -r githooks/* .git/hooks/
      - chmod +x .git/hooks/*
  generate-release:
    vars:
      VERSION:
        sh: git describe --tags --always
    cmds:
      - echo "Generate builds..."
      - sh -c "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/hidra-{{.VERSION}}-linux-amd64/hidra ."
      - sh -c "CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o build/hidra-{{.VERSION}}-linux-arm64/hidra ."
      - sh -c "CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o build/hidra-{{.VERSION}}-linux-arm/hidra ."
      - sh -c "CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o build/hidra-{{.VERSION}}-darwin-amd64/hidra ."
      - sh -c "CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o build/hidra-{{.VERSION}}-darwin-arm64/hidra ."
      - echo "Generate archives..."
      - sh -c "cd build && tar -czf hidra-{{.VERSION}}-linux-amd64.tar.gz hidra-{{.VERSION}}-linux-amd64"
      - sh -c "cd build && tar -czf hidra-{{.VERSION}}-linux-arm64.tar.gz hidra-{{.VERSION}}-linux-arm64"
      - sh -c "cd build && tar -czf hidra-{{.VERSION}}-linux-arm.tar.gz hidra-{{.VERSION}}-linux-arm"
      - sh -c "cd build && tar -czf hidra-{{.VERSION}}-darwin-amd64.tar.gz hidra-{{.VERSION}}-darwin-amd64"
      - sh -c "cd build && tar -czf hidra-{{.VERSION}}-darwin-arm64.tar.gz hidra-{{.VERSION}}-darwin-arm64"
      - echo "Generate checksums..."
      - cd build && sha256sum hidra-{{.VERSION}}-linux-amd64.tar.gz > hidra-{{.VERSION}}-linux-amd64.tar.gz.sha256
      - cd build && sha256sum hidra-{{.VERSION}}-linux-arm64.tar.gz > hidra-{{.VERSION}}-linux-arm64.tar.gz.sha256
      - cd build && sha256sum hidra-{{.VERSION}}-linux-arm.tar.gz > hidra-{{.VERSION}}-linux-arm.tar.gz.sha256
      - cd build && sha256sum hidra-{{.VERSION}}-darwin-amd64.tar.gz > hidra-{{.VERSION}}-darwin-amd64.tar.gz.sha256
      - cd build && sha256sum hidra-{{.VERSION}}-darwin-arm64.tar.gz > hidra-{{.VERSION}}-darwin-arm64.tar.gz.sha256
    silent: true

  clean-release:
    cmds:
      - sh -c "rm -rf build"
    silent: true
