description: "This is a sample to test the HTTP plugin"
tags:
  tenant: "hidra"
interval: "1m"
timeout: "10s"
steps:
  - plugin: http
    action: request
    parameters:
      url: https://www.google.com
