log_level: debug
http_server:
  listen_address: :19090
samples_path: ./configs/hidra/samples
report:
  enabled: true
  # s3:
  #   enabled: true
  #   bucket: hidra-reports
  #   region: ""
  #   access_key_id: "hidratest"
  #   secret_access_key: "hidratest"
  #   endpoint: "minio:9000"
  #   use_ssl: false