name: Create a new release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install CGO_ENABLED dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential
      - name: Download precompiled assets
        run: |
          get_latest_release() {
            curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
              grep '"tag_name":' |                                            # Get tag line
              sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
          }
          LATEST_RELEASE=$(get_latest_release "hidracloud/hidra-frontend")
          mkdir -p api/external/hidra-frontend/app/build
          cd api/external/hidra-frontend/app
          wget https://github.com/hidracloud/hidra-frontend/releases/download/$LATEST_RELEASE/hidra-frontend.tar.gz
          tar -xvzf hidra-frontend.tar.gz
      - name: 'Generate version and dependencies'
        run: |
          make versionize
          make deps

      - name: 'Build & test'
        run: |
          make build

      - name: 'compresss'
        run: |
          make compress
      - name: Set git-tag
        run: echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: true
          draft: true
          files: |
            build/hidra-${{ env.GIT_TAG }}-darwin-amd64.tar.gz
            build/hidra-${{ env.GIT_TAG }}-darwin-arm64.tar.gz
            build/hidra-${{ env.GIT_TAG }}-linux-386.tar.gz
            build/hidra-${{ env.GIT_TAG }}-linux-amd64.tar.gz
            build/hidra-${{ env.GIT_TAG }}-linux-arm64.tar.gz
            build/hidra-${{ env.GIT_TAG }}-linux-arm.tar.gz